name: Flutter CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v2

      # Step 2: Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

          
      - run: flutter pub get

      # Step 4: Build APK
      - run: flutter build apk --release

      # Step 5: Upload APK as artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
