name: Flutter CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

        name: Set up Dart SDK
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.7.0'

          
      - run: flutter pub get

      # Step 4: Build APK
      - run: flutter build apk --release

      # Step 5: Upload APK as artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
